// Generated by https://quicktype.io
export interface Exam {
    id:                     number;
    user_id:                number;
    office_id:              number;
    type:                   string;
    code:                   string;
    name:                   string;
    quantity:               number;
    price:                  number;
    priceWithTaxes:         number;
    taxesAmount:            number;
    exo:                    number;
    measure:                string;
    created_at:             string;
    updated_at:             string;
    laboratory:             number;
    is_servicio_medico:     number;
    reference_commission:   number;
    no_aplica_commission:   number;
    CodigoProductoHacienda: null | string;
    CodigoMoneda:           string;
    cart_quantity:         number;
}


