// Generated by https://quicktype.io

export interface SubscriptionInvoice {
    id:                       number;
    sequence_number:          number;
    customer_sequence_number: number;
    invoice_date:             string;
    due_date:                 string;
    invoice_number:           string;
    reference_number:         null;
    paid_status:              number;
    paid_status_label:        string;
    notes:                    string;
    discount:                 string;
    discount_val:             number;
    sub_total:                number;
    total:                    number;
    tax:                      number;
    currency_id:              number;
    creator_id:               null;
    customer_id:              number;
    created_at:               string;
    updated_at:               string;
    customer:                 Customer;
    items:                    InvoiceItem[];
    currency:                 Currency;
    comprobante_url:          string;
}

export interface Customer {
    id:                       number;
    name:                     string;
    email:                    string;
    avatar_path:              string;
    phone_number:             string;
    whatsapp_number:          null;
    phone_country_code:       string;
    active:                   number;
    provider:                 string;
    provider_id:              string;
    rating_service_cache:     number;
    rating_medic_cache:       number;
    rating_app_cache:         number;
    rating_service_count:     number;
    rating_medic_count:       number;
    rating_app_count:         number;
    commission:               number;
    medic_code:               string;
    ide:                      string;
    fe:                       number;
    pharmacy_notifications:   number;
    clinic_notifications:     number;
    created_at:               string;
    updated_at:               string;
    available_expedient:      number;
    available_expedient_date: null;
    cancel_at:                null;
    accumulated_affiliation:  number;
    current_role_id:          number;
    utiliza_agenda_gps:       number;
    commission_affiliation:   number;
    changed_password:         null;
    fullPhone:                string;
}

export interface InvoiceItem {
    id:                      number;
    subscription_invoice_id: number;
    name:                    string;
    description:             string;
    discount_type:           string;
    price:                   number;
    quantity:                number;
    unit_name:               string;
    discount:                string;
    discount_val:            number;
    tax:                     number;
    total:                   number;
    created_at:              string;
    updated_at:              string;
    taxes:                   any[];
}


// Generated by https://quicktype.io

export interface Currency {
    id:             number;
    code:           string;
    name:           string;
    symbol:         string;
    exchange:       string;
    created_at:     string;
    updated_at:     string;
    exchange_venta: number;
}


